language: rust

rust:
- nightly-2020-02-20
- nightly

os:
- linux
- osx

install:
- rustup target add thumbv6m-none-eabi
- rustup target add thumbv7m-none-eabi
- rustup target add thumbv7em-none-eabi

script:
- cargo test --all --exclude embrio-nrf51 --exclude pca10031 --exclude microbit
- cargo build --target thumbv6m-none-eabi -p embrio-executor -p embrio-nrf51
- (cd examples/pca10031 && cargo build --target thumbv6m-none-eabi -p pca10031 --examples)
- cargo build --target thumbv7m-none-eabi -p embrio-executor
- cargo build --target thumbv7em-none-eabi -p embrio-executor

matrix:
  include:
  - name: rustfmt
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt --all -- --check

  - name: clippy
    install:
    - rustup component add clippy
    - rustup target add thumbv6m-none-eabi
    script:
    - cargo clippy --all --exclude embrio-nrf51 --exclude pca10031 --exclude microbit --all-targets -- -Dwarnings
    - cargo clippy --target thumbv6m-none-eabi -p embrio-nrf51 -p pca10031 --examples -- -Dwarnings

  - name: doc
    script:
    - cargo doc --all --exclude embrio-nrf51 --exclude pca10031 --exclude microbit --no-deps

branches:
  only: [staging, trying, master]
